modLoader = "javafml"
loaderVersion = "[4.0.34,5)"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "https://salt-and-fries.github.io/Salt-s-Inventory-Update/"
issueTrackerURL = "https://github.com/Salt-and-Fries/Salt-s-Inventory-Update/issues"
logoFile = "assets/salts_inventory_update/icon.png"
authors = "Salt"
description = "${description}"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.sophisticated.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.229,21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jei"
type = "optional"
versionRange = "[19.25.1,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "roughlyenoughitems"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "emi"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "sophisticatedcore"
type = "optional"
versionRange = "[1.4.90,2)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "sophisticatedbackpacks"
type = "optional"
versionRange = "[3.25.78,4)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "sophisticatedstorage"
type = "optional"
versionRange = "[1.5.91,2)"
ordering = "AFTER"
side = "BOTH"
